/* The symmetry engine: the square's symmetry group D4 and its 10 subgroups,
   as data. Pure.
   Background: docs/from3Dto2D.md §2 (the showroom's 3D version, G1–G8) and
   §4 (the 2D group).

   ELEMENT CODES, the 2D version of block-showroom's `e = perm*8 + signbits`.
   An element is 3 bits, e = swap<<2 | flipV<<1 | flipU, acting on centred
   coordinates (u, v) = (x - (w-1)/2, y - (h-1)/2) like this:
       1. if swap, (u, v) <- (v, u)        (permute first, as applyG does)
       2. if flipU, u <- -u;  if flipV, v <- -v
   So 0 = identity, 1 = mirror-x, 2 = mirror-y, 3 = rot180, 4 = diagonal
   mirror, 7 = anti-diagonal mirror, 5 and 6 = the two quarter turns.
   Checked when the starter was built: the gens below close to groups of
   order 1,2,2,2,2,2,4,4,4,8. groups.test.js should assert it.

   ORBITS are decided once per orbit, at a representative cell:
     fold: 1  the old fold()'s choice, defects included (old recipes)
     fold: 2  the old choice wherever it was correct, otherwise the
              lexicographic minimum (row, then column). Default for new recipes.
   Measured facts this must reproduce: docs/from3Dto2D.md §3. */

const todo = name => { throw new Error(`not implemented: groups2d.${name} (M1)`); };

export const ELEMENT_COUNT = 8;

/** The 10 subgroups. `legacy` names the old fold() mode that meant this
 *  group, or null if the old app could not produce it. */
export const SUBGROUPS = [
  { id:'none',        name:'C1 · none',                    gens:[],        legacy:'none' },
  { id:'mirror-x',    name:'Cs · mirror left/right',       gens:[1],       legacy:'horizontal' },
  { id:'mirror-y',    name:'Cs · mirror top/bottom',       gens:[2],       legacy:'vertical' },
  { id:'mirror-diag', name:'Cs · mirror on diagonal',      gens:[4],       legacy:null },
  { id:'mirror-anti', name:'Cs · mirror on anti-diagonal', gens:[7],       legacy:null },
  { id:'rot180',      name:'C2 · rotate 180°',             gens:[3],       legacy:'rot180' },
  { id:'rot90',       name:'C4 · pinwheel',                gens:[5],       legacy:'rot90' },
  { id:'quadrant',    name:'D2 · both axis mirrors',       gens:[1, 2],    legacy:'quadrant' },
  { id:'diagonals',   name:'D2 · both diagonal mirrors',   gens:[4, 7],    legacy:null },
  { id:'dihedral',    name:'D4 · all eight',               gens:[1, 4],    legacy:'diagonal' },
];

/** Apply element e to grid cell (x, y) of a w x h grid. @returns {[number, number]} */
export function applyElement(e, x, y, w, h){ return todo('applyElement'); }
/** Code of a·b (apply b, then a). */
export function compose(a, b){ return todo('compose'); }
export function inverse(e){ return todo('inverse'); }
/** True for the four reflections (determinant -1). */
export function isReflection(e){ return todo('isReflection'); }
/** Sorted element codes of the group generated by gens. */
export function closure(gens){ return todo('closure'); }
/** Subgroup record by id, with `els`, `order` and `chiral` filled in. */
export function groupById(id){ return todo('groupById'); }

/** G ∩ Aut(grid): the elements of G that map a w x h grid onto itself.
 *  For square grids this is G; for rectangles it is at most D2.
 *  @returns {{ els:number[], order:number, id:string, reduced:boolean }} */
export function effectiveGroup(id, w, h){ return todo('effectiveGroup'); }

/** Orbit table for one (group, w, h, fold).
 *  @returns {{ rep:Int32Array,         // flat index of each cell's representative
 *              orbitIndex:Uint8Array,  // which element carries the cell to its rep
 *              orbitCount:number }} */
export function orbitTable(id, w, h, fold){ return todo('orbitTable'); }

/** How many of the 8 elements map a finished grid onto itself. Valid on
 *  square grids. On rectangles, count only the elements that fit the grid.
 *  @param {Uint8Array[] | Uint8Array} grid */
export function aut(grid, w, h){ return todo('aut'); }
