/* The symmetry engine: the square's symmetry group D4 and its 10 subgroups,
   as data. Pure.
   Background: docs/from3Dto2D.md §2 (the showroom's 3D version, G1–G8) and
   §4 (the 2D group).

   ELEMENT CODES, the 2D version of block-showroom's `e = perm*8 + signbits`.
   An element is 3 bits, e = swap<<2 | flipV<<1 | flipU, acting on centred
   coordinates (u, v) = (x - (w-1)/2, y - (h-1)/2) like this:
       1. if swap, (u, v) <- (v, u)        (permute first, as applyG does)
       2. if flipU, u <- -u;  if flipV, v <- -v
   So 0 = identity, 1 = mirror-x, 2 = mirror-y, 3 = rot180, 4 = diagonal
   mirror, 7 = anti-diagonal mirror, 5 and 6 = the two quarter turns.
   Checked when the starter was built: the gens below close to groups of
   order 1,2,2,2,2,2,4,4,4,8. groups.test.js should assert it.

   ORBITS are decided once per orbit, at a representative cell:
     fold: 1  the old fold()'s choice, defects included (old recipes)
     fold: 2  the old choice wherever it was correct, otherwise the
              lexicographic minimum (row, then column). Default for new recipes.
   Measured facts this must reproduce: docs/from3Dto2D.md §3. */

const todo = name => { throw new Error(`not implemented: groups2d.${name} (M1b)`); };

export const ELEMENT_COUNT = 8;

/** The 10 subgroups. `legacy` names the old fold() mode that meant this
 *  group, or null if the old app could not produce it. */
export const SUBGROUPS = [
  { id:'none',        name:'C1 · none',                    gens:[],        legacy:'none' },
  { id:'mirror-x',    name:'Cs · mirror left/right',       gens:[1],       legacy:'horizontal' },
  { id:'mirror-y',    name:'Cs · mirror top/bottom',       gens:[2],       legacy:'vertical' },
  { id:'mirror-diag', name:'Cs · mirror on diagonal',      gens:[4],       legacy:null },
  { id:'mirror-anti', name:'Cs · mirror on anti-diagonal', gens:[7],       legacy:null },
  { id:'rot180',      name:'C2 · rotate 180°',             gens:[3],       legacy:'rot180' },
  { id:'rot90',       name:'C4 · pinwheel',                gens:[5],       legacy:'rot90' },
  { id:'quadrant',    name:'D2 · both axis mirrors',       gens:[1, 2],    legacy:'quadrant' },
  { id:'diagonals',   name:'D2 · both diagonal mirrors',   gens:[4, 7],    legacy:null },
  { id:'dihedral',    name:'D4 · all eight',               gens:[1, 4],    legacy:'diagonal' },
];

/** Apply element e to grid cell (x, y) of a w x h grid. @returns {[number, number]} */
export function applyElement(e, x, y, w, h){ return todo('applyElement'); }
/** Code of a·b (apply b, then a). */
export function compose(a, b){ return todo('compose'); }
export function inverse(e){ return todo('inverse'); }
/** True for the four reflections (determinant -1). */
export function isReflection(e){ return todo('isReflection'); }
/** Sorted element codes of the group generated by gens. */
export function closure(gens){ return todo('closure'); }
/** Subgroup record by id, with `els`, `order` and `chiral` filled in. */
export function groupById(id){ return todo('groupById'); }

/** G ∩ Aut(grid): the elements of G that map a w x h grid onto itself.
 *  For square grids this is G; for rectangles it is at most D2.
 *  @returns {{ els:number[], order:number, id:string, reduced:boolean }} */
export function effectiveGroup(id, w, h){ return todo('effectiveGroup'); }

/* ------------------------------------------------------------- the seed region
   Generation evaluates the field, the noise and the masks over a rectangle
   of "seed" cells, in row-major order, because the RNG is consumed in that
   order. Symmetry is then a lookup: every output cell names one seed cell.
   That keeps old sprites byte-identical however the lookup is computed:
     fold:1  the lookup is the old fold() switch, defects included
     fold:2  (M1b) each orbit's representative, chosen inside the same
             rectangle: the old choice where it was correct. */

/** Size of the seed region for a legacy mode. Ported verbatim from reference
 *  `seedDims`. @returns {[number, number]} [sw, sh] */
export function seedDims(w,h,mode){
  const hw = Math.ceil(w/2), hh = Math.ceil(h/2);
  switch(mode){
    case 'horizontal': return [hw,h];
    case 'vertical':   return [w,hh];
    case 'rot180':     return [w,hh];
    case 'quadrant': case 'diagonal': case 'rot90': return [hw,hh];
    default: return [w,h];
  }
}

/** The old fold, ported verbatim from reference `fold`, defects included
 *  (docs/from3Dto2D.md §3). Only fold:1 uses it.
 *  @returns {[number, number]} the seed cell for output cell (x, y) */
export function legacyFold(x,y,w,h,mode){
  const hw = Math.ceil(w/2), hh = Math.ceil(h/2);
  let sx=x, sy=y;
  switch(mode){
    case 'horizontal': if(sx>=hw) sx=w-1-sx; break;
    case 'vertical':   if(sy>=hh) sy=h-1-sy; break;
    case 'quadrant':   if(sx>=hw) sx=w-1-sx; if(sy>=hh) sy=h-1-sy; break;
    case 'rot180':     if(sy>=hh){ sy=h-1-sy; sx=w-1-sx; } break;
    case 'diagonal': {
      if(sx>=hw) sx=w-1-sx; if(sy>=hh) sy=h-1-sy;
      if(hw===hh && sx>sy){ const t=sx; sx=sy; sy=t; }
      break;
    }
    case 'rot90': {
      if(w!==h){ if(sx>=hw) sx=w-1-sx; if(sy>=hh) sy=h-1-sy; break; }
      let g=0;
      while((sx>=hw || sy>=hh) && g++<4){ const nx=h-1-sy, ny=sx; sx=nx; sy=ny; }
      break;
    }
  }
  return [sx,sy];
}

/** The cell -> seed-cell lookup for one (group, w, h, fold).
 *  M1b adds orbitIndex (which element carries each cell to its
 *  representative) and orbitCount.
 *  @returns {{ sw:number, sh:number,
 *              rep:Int32Array }}   // per output cell (y*w + x): seed cell sy*sw + sx */
export function orbitTable(id, w, h, fold){
  const g = SUBGROUPS.find(s => s.id === id);
  if (!g) throw new Error(`unknown symmetry group: ${id}`);
  if (fold !== 1) return todo('orbitTable with fold:2');
  if (!g.legacy) throw new Error(`fold:1 reproduces the old app, which had no ${id} symmetry`);
  const [sw, sh] = seedDims(w, h, g.legacy);
  const rep = new Int32Array(w * h);
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++){
    const [sx, sy] = legacyFold(x, y, w, h, g.legacy);
    rep[y*w + x] = (sx >= 0 && sx < sw && sy >= 0 && sy < sh) ? sy*sw + sx : -1;
  }
  return { sw, sh, rep };
}

/** How many of the 8 elements map a finished grid onto itself. Valid on
 *  square grids. On rectangles, count only the elements that fit the grid.
 *  @param {Uint8Array[] | Uint8Array} grid */
export function aut(grid, w, h){ return todo('aut'); }
