/* The symmetry engine: the square's symmetry group D4 and its 10 subgroups,
   as data. Pure.
   Background: docs/from3Dto2D.md §2 (the showroom's 3D version, G1–G8) and
   §4 (the 2D group).

   ELEMENT CODES, the 2D version of block-showroom's `e = perm*8 + signbits`.
   An element is 3 bits, e = swap<<2 | flipV<<1 | flipU, acting on centred
   coordinates (u, v) = (x - (w-1)/2, y - (h-1)/2) like this:
       1. if swap, (u, v) <- (v, u)        (permute first, as applyG does)
       2. if flipU, u <- -u;  if flipV, v <- -v
   So 0 = identity, 1 = mirror-x, 2 = mirror-y, 3 = rot180, 4 = diagonal
   mirror, 7 = anti-diagonal mirror, 5 and 6 = the two quarter turns.
   Coordinates are handled doubled (U = 2x - (w-1)) so odd and even sizes
   stay in integers.

   ORBITS are decided once per orbit, at a representative cell inside the
   seed region (see below):
     fold: 1  the old fold()'s choice, defects included (old recipes)
     fold: 2  per orbit, the old choice wherever it was correct (the old
              fold sends every member to one cell, and that cell is in the
              orbit); otherwise the first member inside the seed region by
              row, then column. Default for new recipes.
   Measured facts this must reproduce: docs/from3Dto2D.md §3. */

export const ELEMENT_COUNT = 8;

/** The 10 subgroups. `legacy` names the old fold() mode that meant this
 *  group, or null if the old app could not produce it. */
export const SUBGROUPS = [
  { id:'none',        name:'C1 · none',                    gens:[],        legacy:'none' },
  { id:'mirror-x',    name:'Cs · mirror left/right',       gens:[1],       legacy:'horizontal' },
  { id:'mirror-y',    name:'Cs · mirror top/bottom',       gens:[2],       legacy:'vertical' },
  { id:'mirror-diag', name:'Cs · mirror on diagonal',      gens:[4],       legacy:null },
  { id:'mirror-anti', name:'Cs · mirror on anti-diagonal', gens:[7],       legacy:null },
  { id:'rot180',      name:'C2 · rotate 180°',             gens:[3],       legacy:'rot180' },
  { id:'rot90',       name:'C4 · pinwheel',                gens:[5],       legacy:'rot90' },
  { id:'quadrant',    name:'D2 · both axis mirrors',       gens:[1, 2],    legacy:'quadrant' },
  { id:'diagonals',   name:'D2 · both diagonal mirrors',   gens:[4, 7],    legacy:null },
  { id:'dihedral',    name:'D4 · all eight',               gens:[1, 4],    legacy:'diagonal' },
];

/* ------------------------------------------------------------ element algebra */

/** Apply element e to doubled centred coordinates. @returns {[number, number]} */
function act(e, U, V){
  if (e & 4){ const t = U; U = V; V = t; }
  if (e & 1) U = -U;
  if (e & 2) V = -V;
  return [U, V];
}

/** Apply element e to grid cell (x, y) of a w x h grid. On a non-square grid
 *  a swapping element can land outside the grid; effectiveGroup() never
 *  includes those. @returns {[number, number]} */
export function applyElement(e, x, y, w, h){
  const [U, V] = act(e, 2*x - (w-1), 2*y - (h-1));
  return [(U + (w-1)) / 2, (V + (h-1)) / 2];
}

/* Composition table, derived by acting on a probe point whose image
   identifies the element uniquely (|U| != |V|, both non-zero). */
const codeOf = (U, V) => {
  for (let e = 0; e < 8; e++){ const [a, b] = act(e, 1, 2); if (a === U && b === V) return e; }
  throw new Error('not a D4 image');
};
const MUL = new Uint8Array(64), INV = new Uint8Array(8);
for (let a = 0; a < 8; a++) for (let b = 0; b < 8; b++){
  const [u, v] = act(b, 1, 2);
  MUL[a*8 + b] = codeOf(...act(a, u, v));
}
for (let a = 0; a < 8; a++) for (let b = 0; b < 8; b++) if (MUL[a*8 + b] === 0) INV[a] = b;

/** Code of a·b (apply b, then a). */
export function compose(a, b){ return MUL[a*8 + b]; }
export function inverse(e){ return INV[e]; }
/** True for the four reflections (determinant -1): an odd number of swaps and flips. */
export function isReflection(e){ return (((e >> 2) ^ (e >> 1) ^ e) & 1) === 1; }

/** Sorted element codes of the group generated by gens. */
export function closure(gens){
  const set = new Set([0]);
  let grew = true;
  while (grew){
    grew = false;
    for (const a of [...set]) for (const g of gens){
      const c = compose(a, g);
      if (!set.has(c)){ set.add(c); grew = true; }
    }
  }
  return [...set].sort((a, b) => a - b);
}

const GROUP_BY_ID = new Map(SUBGROUPS.map(g => {
  const els = closure(g.gens);
  return [g.id, Object.freeze({ ...g, els, order: els.length, chiral: !els.some(isReflection) })];
}));
const ID_BY_ELS = new Map([...GROUP_BY_ID.values()].map(g => [g.els.join(','), g.id]));

/** Subgroup record by id, with `els`, `order` and `chiral` filled in. */
export function groupById(id){
  const g = GROUP_BY_ID.get(id);
  if (!g) throw new Error(`unknown symmetry group: ${id}`);
  return g;
}

/** The id of the subgroup with exactly these elements, or undefined if they
 *  are not one of the 10. @param {number[]} els  sorted element codes */
export function groupIdOf(els){ return ID_BY_ELS.get(els.join(',')); }

/** G ∩ Aut(grid): the elements of G that map a w x h grid onto itself.
 *  For square grids this is G. On a rectangle only the non-swapping
 *  elements fit, so the result is at most D2 (newdesign.md D3).
 *  @returns {{ els:number[], order:number, id:string, reduced:boolean }} */
export function effectiveGroup(id, w, h){
  const g = groupById(id);
  const els = w === h ? g.els : g.els.filter(e => !(e & 4));
  return { els, order: els.length, id: ID_BY_ELS.get(els.join(',')), reduced: els.length < g.order };
}

/* ------------------------------------------------------------- the seed region
   Generation evaluates the field, the noise and the masks over a rectangle
   of "seed" cells, in row-major order, because the RNG is consumed in that
   order. Symmetry is then a lookup: every output cell names one seed cell.
   That keeps old sprites byte-identical however the lookup is computed:
     fold:1  the lookup is the old fold() switch, defects included
     fold:2  each orbit's representative, chosen inside a rectangle that
             holds a whole fundamental domain; for every legacy group it is
             the old rectangle, so the RNG order is unchanged. */

/** Size of the seed region for a legacy mode. Ported verbatim from reference
 *  `seedDims`. @returns {[number, number]} [sw, sh] */
export function seedDims(w,h,mode){
  const hw = Math.ceil(w/2), hh = Math.ceil(h/2);
  switch(mode){
    case 'horizontal': return [hw,h];
    case 'vertical':   return [w,hh];
    case 'rot180':     return [w,hh];
    case 'quadrant': case 'diagonal': case 'rot90': return [hw,hh];
    default: return [w,h];
  }
}

/** The seed rectangle for fold:2, by EFFECTIVE group. Legacy groups get the
 *  old rectangle. The single diagonal mirrors need the whole grid (their
 *  fundamental domain is a triangle across it); the diagonal pair fits in
 *  the top half. groups.test.js checks every orbit meets its rectangle. */
function seedRect(effId, w, h){
  const hw = Math.ceil(w/2), hh = Math.ceil(h/2);
  switch (effId){
    case 'mirror-x': return [hw, h];
    case 'mirror-y': case 'rot180': case 'diagonals': return [w, hh];
    case 'quadrant': case 'rot90': case 'dihedral': return [hw, hh];
    default: return [w, h];                       // none, mirror-diag, mirror-anti
  }
}

/** The old fold, ported verbatim from reference `fold`, defects included
 *  (docs/from3Dto2D.md §3). Only fold:1 uses it.
 *  @returns {[number, number]} the seed cell for output cell (x, y) */
export function legacyFold(x,y,w,h,mode){
  const hw = Math.ceil(w/2), hh = Math.ceil(h/2);
  let sx=x, sy=y;
  switch(mode){
    case 'horizontal': if(sx>=hw) sx=w-1-sx; break;
    case 'vertical':   if(sy>=hh) sy=h-1-sy; break;
    case 'quadrant':   if(sx>=hw) sx=w-1-sx; if(sy>=hh) sy=h-1-sy; break;
    case 'rot180':     if(sy>=hh){ sy=h-1-sy; sx=w-1-sx; } break;
    case 'diagonal': {
      if(sx>=hw) sx=w-1-sx; if(sy>=hh) sy=h-1-sy;
      if(hw===hh && sx>sy){ const t=sx; sx=sy; sy=t; }
      break;
    }
    case 'rot90': {
      if(w!==h){ if(sx>=hw) sx=w-1-sx; if(sy>=hh) sy=h-1-sy; break; }
      let g=0;
      while((sx>=hw || sy>=hh) && g++<4){ const nx=h-1-sy, ny=sx; sx=nx; sy=ny; }
      break;
    }
  }
  return [sx,sy];
}

/** The cell -> seed-cell lookup for one (group, w, h, fold).
 *  @returns {{ sw:number, sh:number,
 *              rep:Int32Array,         // per output cell (y*w + x): seed cell sy*sw + sx
 *              orbitIndex:Uint8Array,  // fold:2 only: the lowest element code carrying
 *                                      //   the representative to the cell (0 at the rep)
 *              orbitCount:number,      // fold:2 only: number of orbits
 *              effective:object }}     // effectiveGroup() of this (group, w, h)
 */
export function orbitTable(id, w, h, fold){
  const g = groupById(id);
  if (fold === 1) return legacyTable(g, w, h);
  if (fold !== 2) throw new Error(`unknown fold version: ${fold}`);

  const eff = effectiveGroup(id, w, h);
  const [sw, sh] = seedRect(eff.id, w, h);
  // the old fold is only a candidate when it meant this same group on this grid
  const legacyMode = g.legacy && !eff.reduced ? g.legacy : null;
  const N = w * h;
  const rep = new Int32Array(N).fill(-1), orbitIndex = new Uint8Array(N);
  let orbitCount = 0;
  const mx = new Int32Array(eff.order), my = new Int32Array(eff.order);

  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++){
    if (rep[y*w + x] >= 0) continue;
    orbitCount++;
    for (let j = 0; j < eff.order; j++){
      const [ax, ay] = applyElement(eff.els[j], x, y, w, h);
      mx[j] = ax; my[j] = ay;
    }
    // representative: the old choice if it is exact for this orbit…
    let rx = -1, ry = -1;
    if (legacyMode){
      const [fx, fy] = legacyFold(mx[0], my[0], w, h, legacyMode);
      let same = true, member = false;
      for (let j = 0; j < eff.order && same; j++){
        const [gx, gy] = legacyFold(mx[j], my[j], w, h, legacyMode);
        if (gx !== fx || gy !== fy) same = false;
        if (mx[j] === fx && my[j] === fy) member = true;
      }
      if (same && member && fx < sw && fy < sh){ rx = fx; ry = fy; }
    }
    // …otherwise the first member inside the seed rectangle, by row then column
    if (rx < 0){
      for (let j = 0; j < eff.order; j++){
        if (mx[j] >= sw || my[j] >= sh) continue;
        if (rx < 0 || my[j] < ry || (my[j] === ry && mx[j] < rx)){ rx = mx[j]; ry = my[j]; }
      }
      if (rx < 0) throw new Error(`no orbit member of (${x},${y}) in the ${sw}x${sh} seed region (${id} ${w}x${h})`);
    }
    for (let j = 0; j < eff.order; j++){
      const k = my[j]*w + mx[j];
      if (rep[k] >= 0) continue;
      rep[k] = ry*sw + rx;
      // which element carries the representative here: the lowest such code
      let best = 255;
      for (let i = 0; i < eff.order; i++){
        const [bx, by] = applyElement(eff.els[i], rx, ry, w, h);
        if (bx === mx[j] && by === my[j] && eff.els[i] < best) best = eff.els[i];
      }
      orbitIndex[k] = best;
    }
  }
  return { sw, sh, rep, orbitIndex, orbitCount, effective: eff };
}

function legacyTable(g, w, h){
  if (!g.legacy) throw new Error(`fold:1 reproduces the old app, which had no ${g.id} symmetry`);
  const [sw, sh] = seedDims(w, h, g.legacy);
  const rep = new Int32Array(w * h);
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++){
    const [sx, sy] = legacyFold(x, y, w, h, g.legacy);
    rep[y*w + x] = (sx >= 0 && sx < sw && sy >= 0 && sy < sh) ? sy*sw + sx : -1;
  }
  return { sw, sh, rep, orbitIndex: null, orbitCount: null, effective: effectiveGroup(g.id, w, h) };
}

/** How many of the 8 elements map a finished grid onto itself. On a
 *  rectangle only the 4 non-swapping elements can, so the answer is <= 4.
 *  @param {Uint8Array[]} grid  h rows of w cells */
export function aut(grid, w, h){
  let n = 0;
  for (let e = 0; e < 8; e++){
    if (w !== h && (e & 4)) continue;
    let ok = true;
    for (let y = 0; y < h && ok; y++) for (let x = 0; x < w && ok; x++){
      const [ax, ay] = applyElement(e, x, y, w, h);
      if (grid[y][x] !== grid[ay][ax]) ok = false;
    }
    if (ok) n++;
  }
  return n;
}
